# Spearwitch Theme for Alacritty
# Colorscheme from https://rootloops.sh

[colors.primary]
background = "#080808"
foreground = "#e2e2e2"
dim_foreground = "#b9b9b9"
bright_foreground = "#f1f1f1"

[colors.cursor]
text = "#080808"
cursor = "#b9b9b9"

[colors.vi_mode_cursor]
text = "#080808"
cursor = "#ca64f3"

[colors.search.matches]
foreground = "#080808"
background = "#c98b1a"

[colors.search.focused_match]
foreground = "#080808"
background = "#e49f27"

[colors.footer_bar]
foreground = "#e2e2e2"
background = "#222222"

[colors.hints.start]
foreground = "#080808"
background = "#c98b1a"

[colors.hints.end]
foreground = "#080808"
background = "#e49f27"

[colors.selection]
text = "#080808"
background = "#b9b9b9"

# Normal colors
[colors.normal]
black = "#222222"
red = "#f75b72"
green = "#67af34"
yellow = "#c98b1a"
blue = "#509af6"
magenta = "#ca64f3"
cyan = "#1faeae"
white = "#b9b9b9"

# Bright colors
[colors.bright]
black = "#525252"
red = "#fb8590"
green = "#75c73b"
yellow = "#e49f27"
blue = "#77b1fb"
magenta = "#d68af7"
cyan = "#24c6c6"
white = "#f1f1f1"
